export default{
    name:'oppertunity',
    title:'Oppertunity',
    type:'document',
    fields:[
        {
            name:'title',
            title:'Title',
            type:'string'
        },
        {
            name:'participants',
            title:'ForWhom',
            type:'string'
        },
        {
            name:'description',
            title:'Description',
            type:'string'
        },
        {
            name:'openingdate',
            title:'OpeningDate(dd-mm-yyyy)',
            type:'string'
        },
        {
            name:'closingdate',
            title:'ClosingDate(dd-mm-yyyy)',
            type:'string'
        },
        {
            name:'details',
            title:'FileForDetails',
            type:'file'
        },
        {
            name:'imageurl',
            title:'RelatedImages',
            type:'image',
            options:{
                hotspot:true
            }
        },
    ]
}