export default{
    name:'user',
    title:'User',
    type:'document',
    fields:[
        {
            name:'userid',
            title:'UserId',
            type:'string'
        },
        {
            name:'password',
            title:'Password',
            type:'string'
        },
        {
            name:'name',
            title:'Name',
            type:'string'
        },
        {
            name:'rollno',
            title:'RollNo',
            type:'string'
        },
        {
            name:'emailid',
            title:'EmailId',
            type:'string'
        },
        {
            name:'degree',
            title:'Degree',
            type:'string'
        },
        {
            name:'department',
            title:'Department',
            type:'string'
        },
        {
            name:'contactno',
            title:'ContactNo',
            type:'string'
        },
        {
            name:'imageurl',
            title:'ImgUrl',
            type:'image',
            options:{
                hotspot:true
            }
        }
    ]
}